name: osana
description: My custom OS based on Fedora
base-image: ghcr.io/ublue-os/silverblue-main
fedora-version: 40

modules:
  - type: rpm-ostree
    install:
      - tor
      - macchanger
      - git
  - type: files
    files:
      - source: config/backgrounds/
        destination: /usr/share/backgrounds/osana/
  - type: default-flatpaks
    notify: true
    install:
      - org.gnome.TextEditor
  - type: script
    scripts:
      - set-wallpaper.sh
