# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
name: osana
description: My custom OS based on Fedora
base-image: ghcr.io/ublue-os/silverblue-main
image-version: 40 # ИСПРАВЛЕНО: раньше было fedora-version

modules:
  - type: rpm-ostree
    install:
      - tor
      - macchanger
      - git

  - type: files
    files:
      - source: config/backgrounds/
        destination: /usr/share/backgrounds/osana/

  - type: flatpaks # ИСПРАВЛЕНО: используем стандартный модуль вместо default-flatpaks
    install:
      - org.gnome.TextEditor

  - type: script
    scripts:
      - set-wallpaper.sh
