name: bluebuild
on:
  push:
    paths-ignore: [ "**.md" ]
  workflow_dispatch: # Позволяет запускать вручную кнопкой

permissions:
  contents: read
  packages: write
  id-token: write

jobs:
  bluebuild:
    name: Build OsANA
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v6

      - name: Build Image
        uses: blue-build/github-action@v1
        with:
          recipe: 'recipe.yml'
          cosign_private_key: ${{ secrets.SIGNING_SECRET }}
          registry_token: ${{ github.token }}
          maximize_build_space: true
          build_iso: false
